- name: Deploy to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./*"
          target: "/var/www/html"
          rm: true 
          # On utilise 'overwrite: true' et on filtre les dossiers
          overwrite: true
          # Voici comment on exclut proprement avec cette action :
          tar_exec: false
          # On liste ce qu'on veut ignorer (pas d'espaces après les virgules)
          exclude: ".git,.github,test" 
          strip_components: 0
