name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Vérifie bien que ta branche s'appelle main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./*"
          target: "/var/www/html"
          # Nettoie le dossier cible avant de copier pour repartir sur du propre
          rm: true 
          # EXCLUSIONS : On retire .git, les workflows GitHub et ton dossier test
          exclude: ".git,.github,test/" 
          strip_components: 0

      - name: Fix Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
